# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

$react_native = "../node_modules/react-native"

$react_common = [
'Core',
'ART',
'CxxBridge',
'DevSupport',
'RCTText',
'RCTAnimation',
'RCTImage',
'RCTNetwork',
'RCTWebSocket',
'RCTSettings',
]

$react_ios = [
'RCTActionSheet',
'RCTAnimation',
'RCTCameraRoll',
'RCTGeolocation',
'RCTLinkingIOS',
'RCTPushNotification',
'RCTVibration',
]

def common
    third_party = "#{$react_native}/third-party-podspecs"
    
    pod 'yoga',                               :path => "#{$react_native}/ReactCommon/yoga"
    
    pod 'RNDeviceInfo',                       :path => "#{$react_native}-device-info"
    
    pod 'DoubleConversion',                   :podspec => "#{third_party}/DoubleConversion.podspec"
    pod 'glog',                               :podspec => "#{third_party}/GLog.podspec"
    pod 'Folly',                              :podspec => "#{third_party}/Folly.podspec"
    
end

def react_ios
    
end

def react_tvos
    
end

target 'rndm-ios' do
    platform :ios, '9.0'
    common
    pod 'React', path: "#{$react_native}", :subspecs => $react_common + $react_ios
end

target 'rndm-tvos' do
    platform :tvos, '12.1'
    common
    pod 'React', path: "#{$react_native}", :subspecs => $react_common
end

